<?php

namespace Basico\EmpresaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SociedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresasRepository extends EntityRepository
{
    public function empresasActivas($id)
    {
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT s FROM  Basico\EmpresaBundle\Entity\Empresas s
                                         WHERE s.id!=:id
                                         ORDER BY s.nombre');
        $consulta->setParameter('id', $id);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
}
